import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'shahbaz ali',
      email: 'pshahbaz99@gmail.com',
      password: bcrypt.hashSync('125863mas.'),
      isAdmin: true,
    },
    {
      name: 'Ahmad',
      email: ' ahmad99@gmail.com',
      password: bcrypt.hashSync('125863mas.'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'free Shirts',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      desription: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'fit Shirts',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 70,
      brand: 'adidas',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      desription: 'A good Shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'new Shirts',
      slug: 'new-shirt',
      category: 'Shirts',
      image: '/images/shirt4.jpg',
      price: 70,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      desription: 'A good Shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'casual Shirts',
      slug: 'casual-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 70,
      brand: 'Borjan',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      desription: 'A great casual Shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'casual Pant',
      slug: 'casual-pant',
      category: 'pants',
      image: '/images/pants1.jpg',
      price: 70,
      brand: 'Borjan',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      desription: 'A great casual Pant',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'fit Pant',
      slug: 'fit-pant',
      category: 'pants',
      image: '/images/pants2.jpg',
      price: 70,
      brand: 'Borjan',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      desription: 'A great casual Pant',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'Golf Pant',
      slug: 'Golf-pant',
      category: 'pants',
      image: '/images/pants3.jpg',
      price: 70,
      brand: 'Borjan',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      desription: 'A great casual Pant',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'ladies Pant',
      slug: 'ladies-pant',
      category: 'pants',
      image: '/images/pants5.jpg',
      price: 70,
      brand: 'Borjan',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      desription: 'A great casual Pant',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
  ],
};
export default data;
