import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'shahbaz ali',
      email: 'pshahbaz99@gmail.com',
      password: bcrypt.hashSync('125863mas.'),
      isAdmin: true,
    },
    {
      name: 'Ahmad',
      email: ' ahmad99@gmail.com',
      password: bcrypt.hashSync('125863mas.'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'free Shirts',
      slug: 'free-shirt',
      category: 'Shirts',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shir',
      category: 'Shirts',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shi',
      category: 'Shirts',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'freeirt',
      category: 'Shirts',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'fe-shirt',
      category: 'Shirts',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'ree-shirt',
      category: 'Shirts',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shiasrt',
      category: 'Shirts',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shidfrt',
      category: 'Shirts',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-sdfhirt',
      category: 'pants',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-dsfgshirt',
      category: 'pants',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shfgirt',
      category: 'pants',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-sfdghirt',
      category: 'pants',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-sghghhirt',
      category: 'pants',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-hjhshirt',
      category: 'pants',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shijkikrt',
      category: 'pants',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shikikurt',
      category: 'pants',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shuikkirt',
      category: 'pants',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shiiykurt',
      category: 'pants',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shiiuirt',
      category: 'trousers',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shiruut',
      category: 'trousers',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shiriot',
      category: 'trousers',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shirioolt',
      category: 'trousers',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shiriopt',
      category: 'trousers',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shiruiklt',
      category: 'trousers',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shi45rt',
      category: 'suite',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shi5rt',
      category: 'suite',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shir6t',
      category: 'suite',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shir7t',
      category: 'suite',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shir8t',
      category: 'suite',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shir9t',
      category: 'suite',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-sh90irt',
      category: 'suite',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shi0rt',
      category: 'suite',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-shir1t',
      category: 'suite',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'fr2ee-shirt',
      category: 'suite',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free4-shirt',
      category: 'suite',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'f55ree-shirt',
      category: 'suite',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
    {
      name: 'free Shirts',
      slug: 'free-s567hirt',
      category: 'suite',
      image: ['/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 2,
      description: 'A Popular shirt',
      size: ['xl', '2xl', 'small'],
      color: ['red', 'green'],
    },
  ],
};
export default data;
