import Head from 'next/head';

export default function Home() {
  return (
    <div className="light">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-medium text-3xl text-pink-400 dark:text-blue-900">
        my-ecommerce-app
      </div>
    </div>
  );
}
